hyperonecom/h1-cli

- bin/dns/record-set/index.js
- bin/firewall/rule/delete.js
- bin/firewall/rule/index.js
- bin/generic/delete.js
- bin/vm/delete.js
- bin/vm/tag/delete.js
- bin/vm/tag/index.js
There is one place left for the word "remove".
```
$ grep 'remove' bin lib/ -R
bin/vm/delete.js:            { body: { removeDisks: context.args.disk }}
```
> Rename 'remove' to 'delete'

- bin/firewall/rule/add.js
First step on #20 & update help.
> Update firewall help text

- scripts/print_pricing.js
> Add pricing generator

- bin/vm/history/index.js
- bin/vm/index.js
- docs/vm.md
> Rename 'h1 vm queue'

- bin/login/index.js
- bin/network/create/index.js
- bin/user/create/index.js
- lib/interactive.js
Removes a problem with hanging tests via an interactive prompt.
> Raise exception if no TTY & interactive

- bin/vm/index.js
Result of pain-driven-development when preparing a dynamic inventory for Ansible.
> Add tags to VM list

- bin/image/list/index.js
- bin/image/tests.js
```
✖ image › tests › image recommended iso order 
1 test failed
image › tests › image recommended iso order
/home/adas/Devel/h1-cli/bin/image/tests.js:67
66:     });                                                    
67:     t.true(common.vm.sourceImage._id === image_server._id);
68:                                                            
Value is not `true`:
false
common.vm.sourceImage._id === image_server._id
=> false
image_server._id
=> '5b3989d4db77e054081145ad'
image_server
=> {
_id: '5b3989d4db77e054081145ad',
accessRights: [],
createdBy: '572b1a7fa545f3bc466f0983',
createdOn: '2018-07-02T02:11:32.868Z',
description: {
arch: 'x64',
codename: 'bionic beaver',
distro: 'ubuntu',
edition: 'server',
recommended: {
disk: Object { … },
},
release: '18.04',
},
disks: [
{
attachedOn: …
```
> Add test 'image resolver prefer server'

- lib/tests.js
This change showed issues #114.
> Add tests for name resolution in resourceLifeCycle

- bin/disk/create/examples.md
- bin/disk/tests.js
- docs/disk.md
> Fix tests & docs for disk upload

- monitoring/run_monitoring.js
I suppose I changed it yet, but I don't know where this changes was gone.
> Fix format of report

- .travis.yml
- bin/_plugins/api/docs.md
- bin/_plugins/confirmYes/docs.md
- bin/_plugins/outputFormat/docs.md
- bin/_plugins/projectRequired/docs.md
- bin/_plugins/projectRequired/index.js
- bin/config/cli/index.js
- bin/config/index.js
- bin/index.js
- bin/login/index.js
- bin/project/index.js
- bin/rbx.js
- bin/vault/ssh/examples.md
- docs/common-arguments.md
- docs/index.md
- docs/login.md
- docs/project.md
- docs/vault.md
- lib/api.js
- scripts/print_docs.js
To generate documentation for ```rbx``` you need authenticate & next to:
```
SCOPE_NAME="rbx" NODE_ENV="development" npm run docs
```
> Fix build documentation for rbx.

- monitoring/run_monitoring.js
I do not see a better way at this moment to refuse access only for test users to the test tenant.
> Revoke access to tests tenant after tests

- bin/project/tests.js
- monitoring/run_monitoring.js
Provide cmmand history of ```project token access life cycle```.
> Add history to project test

- bin/vault/create/examples.md
- bin/vault/create/index.js
- bin/vault/ssh/index.js
- bin/vault/tests.js
- docs/vault.md
- Fixes #154 
- Add missing ```--command``` to ```vault ssh``` (available in ```vm ssh```).
- Update docs to reflects changes above.
> Add vault snapshot test

- bin/_plugins/outputFormat/index.js
- package-lock.json
- package.json
Subprisingly clear:
```yaml
_id: 5b72ce4c5b2a0b5f4e6d2f0e
name: vm-adoring-hopper
flavour: m2.medium
billingTenant: 5af0bbbcb7802508ad844caa
project: 5af0bbbcb7802508ad844caa
services:
- type: flavour
name: m2.medium
data:
netadp:
- service: 561e7e30a8cfd461e469ad18
disk: []
vm:
maxIPv4: 32
maxhdd: 64
maxNetAdp: 8
cpu: 2
memory: 4
billing: 5b72ce8c6e0e121cb07387a1
sourceService: 58ac4185e01afc73b1547956
_id: 5b72ce8c6e0e121cb07387a2
id: 5b72ce8c6e0e121cb07387a2
modifiedBy: karol.bregula@siecobywatelska.pl
modifiedOn: '2018-08-14T12:42:52.726Z'
createdOn: '2018-08-14T12:42:52.722Z'
createdBy: karol.bregula@siecobywatelska.pl
created: true
processing: false
sourceImage:
name: Ubuntu 18.04 Desktop (bionic beaver)
_id: 5b72422a5b2a0b5f4e6cf980
queue: []
cpu: 2
memory: 4
state: Running
data: …
```
> Add output YAML

- bin/start.js
- lib/api.js
- lib/config.js
Fix for #140. See https://github.com/zeit/pkg/issues/358#issuecomment-415706989 .
> Force NODE_ENV=production in pkg

- bin/_plugins/loginRequired/index.js
- bin/_plugins/projectRequired/index.js
- bin/index.js
- bin/project/token/examples.md
- lib/api.js
- lib/config.js
- lib/epilog/index.js
> Make H1_TOKEN scope-aware

- bin/dns/recordTypes.js
- bin/dns/tests.js
- docs/dns.md
>  Add AAAA for DNS record-set & import & export 

- bin/generic/console/examples.md
- bin/generic/console/index.js
- bin/vault/console/index.js
- bin/vault/index.js
- bin/vault/start/examples.md
- bin/vault/stop/examples.md
- bin/vm/console/examples.md
- bin/vm/console/index.js
- bin/vm/index.js
- docs/vault.md
> Add command to access Vault console

- bin/project/notification/credits/add/index.js
- bin/project/tests.js
- docs/project.md
- monitoring/.env.sample
- package-lock.json
- package.json
Contains #193 
Provides full integrations test for notifications about credits.
> Add threshold integration test via IMAP

- bin/netgw/create/index.js
- bin/network/tests.js
- docs/netgw.md
- lib/tests.js
After fix https://app.asana.com/0/816833263323861/834378829924718 validate that test ```network ip life cycle``` pass using following command:
```bash
npm run test -- --match 'network ip life cycle'
```
> Fix netowork & netgw tests regarding to tags

- bin/generic/tag/add/index.js
- bin/generic/tag/delete/examples.md
- bin/generic/tag/delete/index.js
- bin/vm/nic/index.js
- bin/vm/tests.js
- docs/disk.md
- docs/firewall.md
- docs/image.md
- docs/ip.md
- docs/iso.md
- docs/netgw.md
- docs/network.md
- docs/project.md
- docs/snapshot.md
- docs/vault.md
- docs/vm.md
Need validation after update public API.
> Fix tags for NIC & docs

- bin/login/index.js
> Clarify messages on login

- bin/disk/index.js
- bin/disk/tests.js
- bin/firewall/index.js
- bin/firewall/tests.js
- bin/generic/transfer/examples.md
- bin/generic/transfer/index.js
- bin/image/index.js
- bin/image/tests.js
- bin/ip/index.js
- bin/ip/tests.js
- bin/iso/index.js
- bin/iso/tests.js
- bin/project/index.js
- bin/project/select/index.js
- docs/disk.md
- docs/firewall.md
- docs/image.md
- docs/ip.md
- docs/iso.md
- lib/config.js
- lib/tests.js
- monitoring/run_monitoring.js
> feat: resource transfer

- bin/vault/create/index.js
- bin/vault/credential/password/add/index.js
- bin/vm/create/index.js
- lib/cryptography.js
- package-lock.json
- package.json
Fail on VM create:
```
error: 400 {"_message":"allowBody_98 validation failed","message":"allowBody_98 validation failed: password: Cast to String failed for value \"{ type: 'sha512',\n  value:\n   'qwyRyUpUWM4= MKLIInsyG8dva8HMSni06fvof0aB7JrPFcwuJrDDJ5lzImRpn2exLjfpd/UvvZH3RbkXG8P/URkkI5zBE0gCOA==' }\" at path \"password\"","name":"ValidationError","status":400,"error":{"password":{"message":"Cast to String failed for value \"{ type: 'sha512',\n  value:\n   'qwyRyUpUWM4= MKLIInsyG8dva8HMSni06fvof0aB7JrPFcwuJrDDJ5lzImRpn2exLjfpd/UvvZH3RbkXG8P/URkkI5zBE0gCOA==' }\" at path \"password\"","name":"CastError","stringValue":"\"{ type: 'sha512',\n  value:\n   'qwyRyUpUWM4= MKLIInsyG8dva8HMSni06fvof0aB7JrPFcwuJrDDJ5lzImRpn2exLjfpd/UvvZH3RbkXG8P/URkkI5zBE0gCOA==' …
```
> Add password hashing before send to us

- bin/vm/tests.js
See https://app.asana.com/0/816851498535374/921073450429202 .
> Add integration tests for usermetadata

- lib/tests.js
As I have warned, I need to correct the URL.
> Update OpenAPI schema url

- bin/project/notification/credits/add/index.js
- bin/project/notification/credits/delete/index.js
- bin/project/notification/credits/list/index.js
- bin/project/notification/index.js
Using undocumented endpoint for future generalize & use in agent.
> Simplify code for levels update

- bin/container/log/index.js
I omitted it. This should not be found here.
> Remove debug msg

- bin/vm/create/index.js
- bin/vm/serialport/console/index.js
- lib/websocketTerminal.js
It removes exceptions about writing to closed websocket & unlock close terminal properly.
> Fix websocket terminal close exception

- bin/vm/ssh/ssh.js
Missing scoping due missing property on public API.
> [WIP] Update 'vm ssh' to use dns

- bin/index.js
- bin/registry/create/examples.md
- bin/registry/examples.md
- bin/registry/index.js
- bin/registry/repository/examples.md
- bin/registry/repository/index.js
- bin/registry/repository/tag/index.js
- docs/index.md
- docs/registry.md
- docs/vm.md
> Registry szymon

- bin/env/index.js
- bin/project/token/env/index.js
- lib/shell.js
See values on different platform. 
without pkg & Linux:
with pkg & Linux:
with pkg & Windows:
> Fix env for windows shell bundled by pkg

- .travis.yml
- scripts/build.sh
Change in build.sh to include packaging distribution files into .tar.gz and .zip (in case of Windows) archives
> Distribution packaging

- bin/_plugins/outputFormat/index.js
Patch extracted from #360. Fixes #415, #410
> Fix tags list

- bin/ip/tests.js
- bin/registry/tests.js
- bin/reservation/index.js
- bin/vm/tests.js
- bin/website/tests.js
- docs/reservation.md
- lib/tests.js
And fix zone create for website & registry
> Fix tests of rename in lifecycle

- lib/tests.js
Allows spot issues like #413 . 
Depends on #403
> nic: Add tests of resource create schema

- bin/index.js
- docs/index.md
- scripts/print_docs/index.js
```
$ time NODE_ENV="production" h1 vm list
ID                        NAME                TYPE       STATE    TAGS
5b3f8b7b3adfaa0d10f7bed4  docker-log-archive  a1.micro   Running  zabbix_agent,rsyslog_laas,docker_laas,protected
5b439f6b3adfaa0d10f90820  docker-utils        m2.medium  Running  docker_registry,zabbix_agent,rsyslog_laas,protected
real	0m0.704s
user	0m0.584s
sys	0m0.048s
$ time h1 vm list
ID                        NAME                TYPE       STATE    TAGS
5b3f8b7b3adfaa0d10f7bed4  docker-log-archive  a1.micro   Running  zabbix_agent,rsyslog_laas,docker_laas,protected
5b439f6b3adfaa0d10f90820  docker-utils        m2.medium  Running  docker_registry,zabbix_agent,rsyslog_laas,protected
real	0m1.161s
user	0m1.296s
sys	0m0.076s
> Speedup CLI about 500ms

- bin/_plugins/outputFormat/index.js
- bin/network/tests.js
- bin/registry/tests.js
- bin/website/tests.js
- lib/tests.js
Depends on CNAME answer for A query in new zone
> Fix domain depend test + ip rename + output format

- scripts/travis_deploy.sh
> Allows dot in branch name in docker image

- bin/dns/record-set/index.js
- bin/dns/tests.js
- bin/website/tests.js
> Add tests for CNAME-at-apex

- .travis.yml
Detected deprecated configuration via http://config.travis-ci.com/explore
> Drop warning for TravisCI configuration

- bin/dns/tests.js
Xip.io is pretty flaky (experience). See also: https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/19576
> test: dns, switch from xip.io to nip.io

- scripts/cleanup_project.sh
Limit does not have "id". It's just array of values.
> test: Fix cleanup for "notification credits"

- bin/organisation/tests.js
- bin/reservation/tests.js
Failing constans due:
- reservation overload - @fredericosilva  is aware
- history of project / organisation - https://app.asana.com/0/816833263323861/1162592923976411/f
CC: @fredericosilva
> Disable constant-failing tests

- bin/organisation/tests.js
- bin/reservation/tests.js
Reverts hyperonecom/h1-cli#489
> Revert "Disable constant-failing tests"

- bin/website/tests.js
This is the first time we introduce a performance test in smoke-tests.
```
2020-04-16T09:54:34.355Z node h1 website create --name website-wordpress-installation-1587030874338 --type website --image h1cr.io/website/php-apache\:7.2 --password 840905b051c1905044b66564006689 -o js
2020-04-16T09:54:38.550Z node h1 database create --name database-website-wordpress-installation-1587030878547 --type mysql\:5.7 -o js
2020-04-16T09:54:41.326Z node h1 database credential password add --name website-wordpress-installation-1587030881300 --database 5e982b5f67dfa78866799899 --password 840905b051c1905044b66564006689 -o js
2020-04-16T09:54:43.933Z Upload content to website 5e982b5c67dfa78866799894 at './install.sh'
2020-04-16T09:54:46.030Z [resource: 5e982b5c67dfa78866799894] sh /data/install.sh …
```
> website@tests: Add tests for website performance

- bin/vm/tests.js
- bin/website/tests.js
- lib/ssh.js
@fredericosilva , required to make tests pass again.
> Verify finish cloud-init before cloud-init finish
